import './log.ipc';
import './workspace.ipc';
import './directory-tree.ipc';
import './content-file.ipc';
import './command.ipc';
import './menu.ipc';
import './dialog.ipc';
import './installation.ipc';
import './ssh.ipc';